# Generated by Django 5.0.7 on 2024-07-11 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_scrapeddata_delete_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapeddata',
            name='description',
        ),
        migrations.RemoveField(
            model_name='scrapeddata',
            name='url',
        ),
    ]
