# Generated by Django 5.0.7 on 2024-07-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_submenu_title_sub3menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub3menu',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
