# Generated by Django 5.0.7 on 2024-07-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_scrapeddata_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
