# Generated by Django 5.0.7 on 2024-07-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_scrapeddata_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
