# Generated by Django 5.0.7 on 2024-07-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nltk_app', '0002_trainingquery_remove_message_conversation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('expected_response', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='trainingresponse',
            name='query',
        ),
        migrations.DeleteModel(
            name='TrainingQuery',
        ),
        migrations.DeleteModel(
            name='TrainingResponse',
        ),
    ]
