# Generated by Django 5.0.7 on 2024-07-14 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nltk_app', '0003_trainingdata_remove_trainingresponse_query_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingData',
        ),
    ]
