# Generated by Django 5.0.7 on 2024-07-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nltk_app', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='intent',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.DeleteModel(
            name='Intent',
        ),
        migrations.DeleteModel(
            name='Pattern',
        ),
    ]
